In [8]:
import pandas as pd
import seaborn as sns
import numpy as np

%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

Load the data

In [9]:
ecg = pd.read_csv("D:/22-1/ml/termp/ECG_FeaturesExtracted.csv")

In [10]:
ecg

Quad_Cat          Mean       Min       Max  MeanRR  MedianRR  MinRR  \
0           1  9.404760e-07 -0.741816  0.919643    1531    1562.0     14   
1           0  4.330640e-07 -0.386809  0.452853    1582    1599.0   1336   
2           0  9.034100e-06 -0.311829  0.398468    1637    1659.5   1421   
3           3 -1.607510e-05 -0.330817  0.405026    1724    1727.0   1574   
4           1  3.100000e-06 -0.303375  0.390093    1634    1654.0   1354   
..        ...           ...       ...       ...     ...       ...    ...   
307         2  5.233020e-06 -0.326834  0.226890    8871    2517.0   1641   
308         0  3.885170e-05 -0.337467  0.267606    1942    2069.0     78   
309         1  2.666020e-05 -0.327919  0.268247    1476    1342.5     57   
310         3  1.031120e-04 -0.318627  0.254868    1758    1958.0    841   
311         3 -9.759030e-05 -0.312999  0.224749    1711    1397.0    826   

     MaxRR            LF            HF           VLF         Ibi        Bpm  \
0     3130  1.194750e-09  2.231830e-06  4.403520e-11  763.823158  78.559522   
1     1695  1.060430e-10  1.283180e-07  2.946190e-12  794.173554  75.573801   
2     1798  2.679310e-09  6.225430e-08  8.177790e-10  781.661290  76.868796   
3     1895  1.345210e-08  1.348180e-07  4.147950e-09  720.920000  83.241534   
4     1837  7.953400e-10  1.135080e-07  2.688100e-10  779.417204  77.044532   
..     ...           ...           ...           ...         ...        ...   
307  61273  2.869180e-09  4.452460e-08  4.620720e-10  729.159744  82.312438   
308   5059  1.020350e-07  2.892450e-07  3.324850e-08  746.706767  80.452141   
309   3401  5.007920e-08  1.548030e-07  1.709190e-08  735.177570  81.646377   
310   3610  3.491200e-07  1.011910e-06  1.064670e-07  730.368159  82.298379   
311   6894  2.898780e-07  7.576280e-07  9.531870e-08  752.693548  79.835491   

           Sdnn        Sdsd        Rmssd     Pnn50     pnn20  Pnn50pnn20  
0    245.875789  469.052909  102253.7461  0.478903  0.481013    0.995614  
1    240.813984  468.780827  127309.4367  0.477178  0.477178    1.000000  
2    263.073272  492.561472  130746.3059  0.459459  0.459459    1.000000  
3    243.280744  419.797884  163218.7363  0.424749  0.438127    0.969466  
4    266.303744  502.914461  121215.4100  0.480603  0.487069    0.986726  
..          ...         ...          ...       ...       ...         ...  
307  206.105776  313.428744  150982.0997  0.445513  0.509615    0.874214  
308  217.496871  368.406657  129086.9816  0.615578  0.623116    0.987903  
309  193.495058  311.419739  114921.7850  0.531616  0.562061    0.945833  
310  188.080997  310.820126  100618.0409  0.580000  0.585000    0.991453  
311  210.404775  356.161518  108629.2813  0.648649  0.648649    1.000000  

[312 rows x 19 columns]

Add new labels (Arousal, Valence, LFHF_Ratio)

In [11]:
ecg['LFHF_Ratio'] = ecg.apply(lambda x : x['LF']/x['HF'], axis=1)

In [12]:
def getArousal(quad):
    if quad==0 or quad==3:
        arousal = 1
    else:
        arousal = 0
    return arousal

def getValence(quad):
    if quad==0 or quad==1:
        valence = 1
    else:
        valence = 0
    return valence

In [13]:
ecg['Arousal'] = ecg.apply(lambda x : getArousal(x['Quad_Cat']), axis=1)
ecg['Valence'] = ecg.apply(lambda x : getValence(x['Quad_Cat']), axis=1)

In [14]:
ecg

Quad_Cat          Mean       Min       Max  MeanRR  MedianRR  MinRR  \
0           1  9.404760e-07 -0.741816  0.919643    1531    1562.0     14   
1           0  4.330640e-07 -0.386809  0.452853    1582    1599.0   1336   
2           0  9.034100e-06 -0.311829  0.398468    1637    1659.5   1421   
3           3 -1.607510e-05 -0.330817  0.405026    1724    1727.0   1574   
4           1  3.100000e-06 -0.303375  0.390093    1634    1654.0   1354   
..        ...           ...       ...       ...     ...       ...    ...   
307         2  5.233020e-06 -0.326834  0.226890    8871    2517.0   1641   
308         0  3.885170e-05 -0.337467  0.267606    1942    2069.0     78   
309         1  2.666020e-05 -0.327919  0.268247    1476    1342.5     57   
310         3  1.031120e-04 -0.318627  0.254868    1758    1958.0    841   
311         3 -9.759030e-05 -0.312999  0.224749    1711    1397.0    826   

     MaxRR            LF            HF  ...        Bpm        Sdnn  \
0     3130  1.194750e-09  2.231830e-06  ...  78.559522  245.875789   
1     1695  1.060430e-10  1.283180e-07  ...  75.573801  240.813984   
2     1798  2.679310e-09  6.225430e-08  ...  76.868796  263.073272   
3     1895  1.345210e-08  1.348180e-07  ...  83.241534  243.280744   
4     1837  7.953400e-10  1.135080e-07  ...  77.044532  266.303744   
..     ...           ...           ...  ...        ...         ...   
307  61273  2.869180e-09  4.452460e-08  ...  82.312438  206.105776   
308   5059  1.020350e-07  2.892450e-07  ...  80.452141  217.496871   
309   3401  5.007920e-08  1.548030e-07  ...  81.646377  193.495058   
310   3610  3.491200e-07  1.011910e-06  ...  82.298379  188.080997   
311   6894  2.898780e-07  7.576280e-07  ...  79.835491  210.404775   

           Sdsd        Rmssd     Pnn50     pnn20  Pnn50pnn20  LFHF_Ratio  \
0    469.052909  102253.7461  0.478903  0.481013    0.995614    0.000535   
1    468.780827  127309.4367  0.477178  0.477178    1.000000    0.000826   
2    492.561472  130746.3059  0.459459  0.459459    1.000000    0.043038   
3    419.797884  163218.7363  0.424749  0.438127    0.969466    0.099780   
4    502.914461  121215.4100  0.480603  0.487069    0.986726    0.007007   
..          ...          ...       ...       ...         ...         ...   
307  313.428744  150982.0997  0.445513  0.509615    0.874214    0.064440   
308  368.406657  129086.9816  0.615578  0.623116    0.987903    0.352763   
309  311.419739  114921.7850  0.531616  0.562061    0.945833    0.323503   
310  310.820126  100618.0409  0.580000  0.585000    0.991453    0.345011   
311  356.161518  108629.2813  0.648649  0.648649    1.000000    0.382613   

     Arousal  Valence  
0          0        1  
1          1        1  
2          1        1  
3          1        0  
4          0        1  
..       ...      ...  
307        0        0  
308        1        1  
309        0        1  
310        1        0  
311        1        0  

[312 rows x 22 columns]

Standard Scaler

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
ecg_all_features_without_label = ecg.iloc[:, 1:-2]

In [21]:
scaler = StandardScaler()
ecg_all_std = scaler.fit_transform(ecg_all_features_without_label)

ecg_all_std_df = pd.DataFrame(ecg_all_std, columns=['Mean', 'Min', 'Max', 'MeanRR', 'MedianRR', 'MinRR',
       'MaxRR', 'LF', 'HF', 'VLF', 'Ibi', 'Bpm', 'Sdnn', 'Sdsd', 'Rmssd','Pnn50', 'pnn20', 'Pnn50pnn20', 'LFHF_Ratio'])
ecg_all_std_df['Quad_Cat'] = ecg.loc[:, ['Quad_Cat']]
ecg_all_std_df['Arousal'] = ecg.loc[:, ['Arousal']]
ecg_all_std_df['Valence'] = ecg.loc[:, ['Valence']]

### Linear Regression

1. Valence

In [25]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [26]:
X = ecg_all_std_df.loc[:, ['Mean', 'Min', 'Max', 'MeanRR', 'MedianRR', 'MinRR',
       'MaxRR', 'LF', 'HF', 'VLF', 'Ibi', 'Bpm', 'Sdnn', 'Sdsd', 'Rmssd','Pnn50', 'pnn20', 'Pnn50pnn20', 'LFHF_Ratio']]
y = ecg_all_std_df.loc[:, ['Valence']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state = 11)

In [27]:
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)
lin_reg.intercept_, lin_reg.coef_

(array([0.58093386]),
 array([[ 4.79991055e-02, -3.83360481e-02, -2.41334296e-02,
          2.41163092e-02, -6.34879553e-02, -1.31562957e-04,
          2.35013497e-02, -2.14103498e+00,  3.44554729e-02,
          3.27365656e+00,  3.16413925e-01,  2.03151152e-01,
         -1.22974276e-01,  1.60841691e-03,  6.89964225e-03,
         -6.27372141e-01,  4.43158776e-01,  4.20999943e-01,
         -1.94992948e-02]]))

In [28]:
cols = np.array(['Mean', 'Min', 'Max', 'MeanRR', 'MedianRR', 'MinRR',
       'MaxRR', 'LF', 'HF', 'VLF', 'Ibi', 'Bpm', 'Sdnn', 'Sdsd', 'Rmssd','Pnn50', 'pnn20', 'Pnn50pnn20', 'LFHF_Ratio']).flatten()

In [29]:
coeff = pd.Series(data=lin_reg.coef_[0], index=cols)
coeff.sort_values(ascending = False)

VLF           3.273657
pnn20         0.443159
Pnn50pnn20    0.421000
Ibi           0.316414
Bpm           0.203151
Mean          0.047999
HF            0.034455
MeanRR        0.024116
MaxRR         0.023501
Rmssd         0.006900
Sdsd          0.001608
MinRR        -0.000132
LFHF_Ratio   -0.019499
Max          -0.024133
Min          -0.038336
MedianRR     -0.063488
Sdnn         -0.122974
Pnn50        -0.627372
LF           -2.141035
dtype: float64

In [30]:
y_pred = lin_reg.predict(X_test)

In [31]:
mse = mean_squared_error(y_pred, y_test)
print("mse: ", mse)
print("rmse: ", np.sqrt(mse))

mse:  14.471137792547824
rmse:  3.804094871654468


2. Arousal

In [32]:
X = ecg_all_std_df.loc[:, ['Mean', 'Min', 'Max', 'MeanRR', 'MedianRR', 'MinRR',
       'MaxRR', 'LF', 'HF', 'VLF', 'Ibi', 'Bpm', 'Sdnn', 'Sdsd', 'Rmssd','Pnn50', 'pnn20', 'Pnn50pnn20', 'LFHF_Ratio']]
y = ecg_all_std_df.loc[:, ['Arousal']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state = 11)

In [33]:
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)
lin_reg.intercept_, lin_reg.coef_

(array([0.33556891]),
 array([[-0.02444257,  0.01385944, -0.03617094,  0.08537435, -0.13112023,
         -0.0198597 , -0.02597832,  3.37256152,  0.03036418, -5.1272707 ,
          0.39818613,  0.40561687,  0.04990562, -0.05546588, -0.02138043,
          0.11920395, -0.0631509 ,  0.01325445, -0.02156797]]))

In [34]:
cols = np.array(['Mean', 'Min', 'Max', 'MeanRR', 'MedianRR', 'MinRR',
       'MaxRR', 'LF', 'HF', 'VLF', 'Ibi', 'Bpm', 'Sdnn', 'Sdsd', 'Rmssd','Pnn50', 'pnn20', 'Pnn50pnn20', 'LFHF_Ratio']).flatten()

In [35]:
coeff = pd.Series(data=lin_reg.coef_[0], index=cols)
coeff.sort_values(ascending = False)

LF            3.372562
Bpm           0.405617
Ibi           0.398186
Pnn50         0.119204
MeanRR        0.085374
Sdnn          0.049906
HF            0.030364
Min           0.013859
Pnn50pnn20    0.013254
MinRR        -0.019860
Rmssd        -0.021380
LFHF_Ratio   -0.021568
Mean         -0.024443
MaxRR        -0.025978
Max          -0.036171
Sdsd         -0.055466
pnn20        -0.063151
MedianRR     -0.131120
VLF          -5.127271
dtype: float64

In [36]:
y_pred = lin_reg.predict(X_test)

In [37]:
mse = mean_squared_error(y_pred, y_test)
print("mse: ", mse)
print("rmse: ", np.sqrt(mse))

mse:  35.49396432296562
rmse:  5.957681119610684


3. Quad_Cat

In [38]:
X = ecg_all_std_df.loc[:, ['Mean', 'Min', 'Max', 'MeanRR', 'MedianRR', 'MinRR',
       'MaxRR', 'LF', 'HF', 'VLF', 'Ibi', 'Bpm', 'Sdnn', 'Sdsd', 'Rmssd','Pnn50', 'pnn20', 'Pnn50pnn20', 'LFHF_Ratio']]
y = ecg_all_std_df.loc[:, ['Quad_Cat']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state = 11)

In [39]:
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)
lin_reg.intercept_, lin_reg.coef_

(array([1.3520783]),
 array([[-0.14531843,  0.09405278,  0.04064986,  0.19195245, -0.14735094,
         -0.07537585, -0.16609598,  3.47165218, -0.02827544, -5.20493809,
         -0.78210846, -0.45035886,  0.36989583, -0.13308497, -0.04365352,
          0.50080918, -0.35141932, -0.47395216,  0.08293086]]))

In [40]:
cols = np.array(['Mean', 'Min', 'Max', 'MeanRR', 'MedianRR', 'MinRR',
       'MaxRR', 'LF', 'HF', 'VLF', 'Ibi', 'Bpm', 'Sdnn', 'Sdsd', 'Rmssd','Pnn50', 'pnn20', 'Pnn50pnn20', 'LFHF_Ratio']).flatten()

In [41]:
coeff = pd.Series(data=lin_reg.coef_[0], index=cols)
coeff.sort_values(ascending = False)

LF            3.471652
Pnn50         0.500809
Sdnn          0.369896
MeanRR        0.191952
Min           0.094053
LFHF_Ratio    0.082931
Max           0.040650
HF           -0.028275
Rmssd        -0.043654
MinRR        -0.075376
Sdsd         -0.133085
Mean         -0.145318
MedianRR     -0.147351
MaxRR        -0.166096
pnn20        -0.351419
Bpm          -0.450359
Pnn50pnn20   -0.473952
Ibi          -0.782108
VLF          -5.204938
dtype: float64

In [42]:
y_pred = lin_reg.predict(X_test)

In [43]:
mse = mean_squared_error(y_pred, y_test)
print("mse: ", mse)
print("rmse: ", np.sqrt(mse))

mse:  36.09812180466607
rmse:  6.008171252940953
